"""Generate the two committed example logs used in the README quickstart.

    python examples/build_examples.py

Produces:
  examples/clean.eval   -> audits PASS
  examples/broken.eval  -> audits FAIL (a model-graded scorer that graded nothing
                           plus a silently dropped errored sample)

Both are tiny, generated by Inspect's real writer, and safe to publish.
"""

from __future__ import annotations

import copy
import math
import os
import shutil
import warnings

from inspect_ai import Task
from inspect_ai import eval as inspect_eval
from inspect_ai._util.error import EvalError
from inspect_ai.dataset import Sample
from inspect_ai.log import read_eval_log, write_eval_log
from inspect_ai.model import GenerateConfig, ModelOutput, get_model
from inspect_ai.scorer import match
from inspect_ai.scorer._metric import Score

warnings.filterwarnings("ignore")

HERE = os.path.dirname(os.path.abspath(__file__))


def build_clean(path: str) -> None:
    model = get_model(
        "mockllm/model",
        custom_outputs=[
            ModelOutput.from_content("mockllm/model", "4"),
            ModelOutput.from_content("mockllm/model", "Paris"),
        ],
        config=GenerateConfig(temperature=0.0, seed=42),
    )
    task = Task(
        dataset=[
            Sample(input="2+2?", target="4"),
            Sample(input="capital of France?", target="Paris"),
        ],
        scorer=match(),
    )
    tmp = os.path.join(HERE, "_tmp")
    if os.path.isdir(tmp):
        shutil.rmtree(tmp)
    logs = inspect_eval(task, model=model, display="none", log_dir=tmp)
    shutil.copyfile(logs[0].location, path)
    shutil.rmtree(tmp)


def build_broken(clean_path: str, out: str) -> None:
    log = read_eval_log(clean_path)
    # 1) a silently dropped errored sample
    s0 = log.samples[0]
    s0.error = EvalError(message="RuntimeError: tool timed out",
                         traceback="Traceback...\nRuntimeError: tool timed out",
                         traceback_ansi="tool timed out")
    s0.scores = {}
    log.results.completed_samples -= 1
    sc = log.results.scores[0]
    sc.scored_samples = (sc.scored_samples or log.results.total_samples) - 1
    sc.unscored_samples = (sc.unscored_samples or 0) + 1
    # 2) a model-graded scorer whose grader returned no parseable grade
    total = log.results.total_samples
    mg = copy.deepcopy(log.results.scores[0])
    mg.name = "model_graded_qa"
    mg.scorer = "model_graded_qa"
    mg.params = {"model": "mockllm/grader"}
    mg.scored_samples = 0
    mg.unscored_samples = total
    log.results.scores.append(mg)
    for s in log.samples:
        s.scores = dict(s.scores or {})
        s.scores["model_graded_qa"] = Score(
            value=math.nan,
            explanation="Grade not found in model output: (no grade line)",
        )
    write_eval_log(log, out)


def main() -> None:
    clean = os.path.join(HERE, "clean.eval")
    broken = os.path.join(HERE, "broken.eval")
    build_clean(clean)
    build_broken(clean, broken)
    for f in (clean, broken):
        print(os.path.relpath(f), os.path.getsize(f), "bytes")


if __name__ == "__main__":
    main()
